### ISSUE TITLE
Notifications not received when app is closed

### ISSUE THREAD

**Issue by vijirajtp** [calonso/rails-push-notifications#19] opened 2018-03-06 10:40 UTC
Hello,

I am trying to send notifications to android device. When app is open in my device, i am getting push notification, but its closed there is no notifications receiving. Here is the code which i am doing:

    notification = app.notifications.build(
        destinations: [DEVICE_TOKEN_HERE],
        data: { text: message, key: value, key: value }
      )
      app.push_notifications if notification.save

where *key* are the extra parameters i want to pass. This code works when the app is opened. Is there anything wrong in the code ? or do i need to add some other settings to receive the notification when app is closed? Your kind help is highly appreciated.

Thanks in advance.

**Comment by calonso** [comment] 2018-03-09 08:43
Hi @vijirajtp I'd say the issue is probably on the device end, or at least not on the rails gem as it's clear that notifications are successfully pushed.

I don't know enough Android to help you there, but probably there are different ways of handling notifications when the app is open or not.

**Comment by calonso** [comment] 2018-03-09 08:43
I'm closing it as it seems to be an issue somewhere outside this gem. Please reopen it if required.

**Closed as completed by calonso** 2018-03-09 08:43 UTC

**Comment by vijirajtp** [comment] 2018-03-09 12:02
Hi Carlos

Thanks for the response. I will check it in device end. 

But is it possible to send data message and notification message both using this gem?
